### ISSUE TITLE
Skip request validation

### ISSUE THREAD

**Issue by yanlyan** [hotmeteor/spectator#107] opened 2022-07-06 07:51 UTC
Hello, is there any feature to opt-out of the request validation like 
`$this->skipRequestValidation()` ?

because it automatically validates the request even without `assertValidRequest()`

thank you

**Comment by philsturgeon** [comment] 2022-07-19 17:44
Potentially a duplicate of #92.

**Comment by hotmeteor** [comment] 2022-08-08 13:38
@yanlyan This is now available in the latest release. Simply omit the validations you don't want.

**Closed by hotmeteor** 2022-08-08 13:38 UTC
