### ISSUE TITLE
No error when a property isn't present in schema but present in response and reverse

### ISSUE THREAD

**Issue by jechazelle** [hotmeteor/spectator#131] opened 2022-10-05 10:44 UTC
Hi community, 👋

I tried spectator, thank you for this package !
I read this [article](https://laravel-news.com/test-your-openapi-implementation-with-spectator) to try this package, and I have no error when I remove a property from schema or declaration.

For exemple:
* I removed this line **@OA\Property(property="name", type="string", example="name")** from Schema Tag, if I understand, when I execute my test, I must have an error because I have a **name** property on the response present, but not declare in the schema.
* I tried to execute the "reverse": declare a property on the response (test property on TagRepository), and not in the schema, but always not error, the test passed.

Do you know where is the error please?

Thank you so much for your answer!

Currently, I have this: 

    /**
    * @OA\Schema(schema="Tag", description="Tag schema",
    *     @OA\Property(property="uuid", type="string", example="0d46a17a-d570-4025-ad4b-4257ede88bed"),
    *     @OA\Property(property="name", type="string", example="name"),
    *     @OA\Property(property="code", type="string", example="code")
    * )
    */

and

    /**
    * @OA\Get(path="/tags", operationId="getTags", tags={"Tags"}, summary="Get List Of Tag", description="Return all tags",
    *     @OA\Response(response=200, description="Tags successfully listed",
    *         @OA\JsonContent(
    *             @OA\Property(property="status", type="string", example="success"),
    *             @OA\Property(property="data", type="array", @OA\Items(ref="#/components/schemas/Tag")),
    *             @OA\Property(property="message", type="string", example="Tags successfully listed")
    *         )
    *     )
    * )
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $tags = $this->tagRepository->getAll();

        return response()->json(['status' => 'success', 'data' => $tags, 'message' => 'Tags successfully listed'], 200);
    }

on my test, I have this: 

    <?php

    namespace Tests\Feature\Api\Tag;

    use Illuminate\Foundation\Testing\RefreshDatabase;
    use Illuminate\Foundation\Testing\WithFaker;
    use Tests\TestCase;
    use Spectator\Spectator;

    class ApiTag extends TestCase
    {
        use RefreshDatabase;

        public function setUp(): void
        {
            parent::setUp();

            Spectator::using('api-docs.json');
        }

        /**
         * A basic feature test example.
         *
         * @return void
         */
        public function test_get_tags()
        {
            $this->seed();

            $response = $this->getJson('/api/tags');
            
            $response
                ->assertValidRequest()
                ->assertValidResponse(200);
        }
    }

> on my api-docs.jons, I have this:

Tags:

    "/tags": {
        "get": {
            "tags": [
                "Tags"
            ],
            "summary": "Get List Of Tag",
            "description": "Return all tags",
            "operationId": "getTags",
            "responses": {
                "200": {
                    "description": "Tags successfully listed",
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "status": {
                                        "type": "string",
                                        "example": "success"
                                    },
                                    "data": {
                                        "type": "array",
                                        "items": {
                                            "$ref": "#/components/schemas/Tag"
                                        }
                                    },
                                    "message": {
                                        "type": "string",
                                        "example": "Tags successfully listed"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
    },

Components:

    "Tag": {
        "description": "Tag schema",
        "properties": {
            "uuid": {
                "type": "string",
                "example": "0d46a17a-d570-4025-ad4b-4257ede88bed"
            },
            "name": {
                "type": "string",
                "example": "name"
            },
            "code": {
                "type": "string",
                "example": "code"
            }
        },
        "type": "object"
    },

* "laravel/framework": "^9.22",
* "hotmeteor/spectator": "^1.7"

**Comment by ricardonolan** [comment] 2022-11-10 10:35
Having a similar issue, test passes regardless of whether the response matches the schema

**Comment by bastien-phi** [comment] 2022-12-23 11:13
This behavior is not caused by Spectator but is a consequence of the Json Schema specification.

An object is considered valid if all properties in the schema definition (here your openapi file) matches the properties of the object.

In your case, whith the definition 
```
"Tag": {
    "description": "Tag schema",
    "properties": {
        "uuid": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "code": {
            "type": "string"
        }
    },
    "type": "object"
},
```
an object 
```
{
 "uuid": "0d46a17a-d570-4025-ad4b-4257ede88bed",
 "name": "name",
 "code": "code",
 "foo": "foo"
}
```
is completely valid because all properties of the definition are valid.

If you want to forbid additional properties, you have to explicit it with 
```
"Tag": {
    "description": "Tag schema",
    "properties": {
        "uuid": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "code": {
            "type": "string"
        }
    },
    "type": "object",
    "additionalProperties": false
},
```

With that, your object won't be valid anymore and Spectator will give you a
```
Additional object properties are not allowed: foo
```

Hope it will help

**Comment by bastien-phi** [comment] 2024-01-31 19:47
Closing this issue as it looks like it was only a misunderstanding of usage.

@jechazelle Feel free to reach us if your problem still exists

**Closed by bastien-phi** 2024-01-31 19:47 UTC
